[versions]
asm = "9.7"
classgraph = "4.8.172"
junit = "5.10.2"
gson = "2.11.0"
smile = "3.1.1"
gradleApi = "8.7"

[libraries]
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
smile-core = { module = "com.github.haifengl:smile-core", version.ref = "smile" }

[bundles]
asm = ["asm-core", "asm-tree", "asm-util"]
